
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Nanum_Myeongjo } from "next/font/google";  //imported
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nanumMyeongjo = Nanum_Myeongjo({
  weight: ['400', '700', '800'], // Available weights
  subsets: ['latin'],            // Or ['latin', 'korean'] if needed
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={nanumMyeongjo.className}
      >
        {children}
      </body>
    </html>
  );
}
